---
- hosts: appservers
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - "/tmp/workspace/cloud_automation/create_gcp_instance/GCE_Instance/group_vars/appservers"
  roles:
    - "/tmp/workspace/cloud_automation/create_gcp_instance/GCE_Instance/ansible/roles/ConfigureBli"
  gather_facts: False
...